name: 'Install InnoSetup'
description: 'cross platform action for installing innosetup'
runs:
  using: 'composite'
  steps:
    - id: installinno
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get install innosetup -y
    - id: test
      shell: bash
      run: innosetup-compiler --version

branding:
  icon: package
  color: blue
